server:
  port: 8380

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

#  sql:
#    init:
#      mode: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug